### ISSUE TITLE
MinSDK supported

### ISSUE THREAD

**Issue by alex73** [a-student/BetterVectorDrawable#18]
Sorry, I created issue because I can't find your email.
You wrote: "The VectorDrawable implementation for Android 4.0+ (API level 14 or greater).".
But when I compiled my application with BetterVectorDrawable for API level 10, it still works. Probably because I'm using AppCompat.
Are there any parts of BetterVectorDrawable that will not work under API level 10 ?

**Comment by a-student** [comment]
Hi!

> Sorry, I created issue because I can't find your email.

It is ok, you did it right way.

> when I compiled my application with BetterVectorDrawable for API level 10, it still works.

There are two explanations for that:
1) The lib may work on API level 10. We just do not test it on api levels less than 14, because share of those android versions is small.
2) Possibly you did not specify `generatedDensities = []`, so the lib is not actually used.

> Are there any parts of BetterVectorDrawable that will not work under API level 10 ?

Don't know. I wasn't considering this api level when i ported the code.

For now i close the issue, but feel free to reopen and ask more questions.
