### ISSUE TITLE
Incorrect displaying of images

### ISSUE THREAD

**Issue by Vasilevsrus** [a-student/BetterVectorDrawable#4]
Hello, I found your librarry very interesting, but I have an issue with displaying of my vector images. Some of them displays incorrectly (some parts of pictures dissapear), and I'm not really sure why. I used your online converter. And the main thing that confuses me is sometimes they looks normal (not all of them, but still). 
So I will be really pleased, if you help me resolve this problem ) 
And there is a link to an archive with my project, where drawables was made by your converter
http://rghost.ru/6l46wj7h7

**Comment by a-student** [comment]
Hello! Thank you for the report. It seems that the VectorDrawable implementation has bug in clip-path handling. I will try to resolve the issue this weekend.
By the way, learn_place_animal_hippo.xml is not hippo, this is rhino. Very nice images, though!

**Comment by Vasilevsrus** [comment]
Thank you for quick respond, I'll be waiting! And I take into account about rhino)

**Comment by a-student** [comment]
I released the new lib version today, please, update the dependency in **build.gradle** (Module: app):

``` groovy
dependencies {
    …
    compile 'com.bettervectordrawable:lib:0.6+'
}
```

Vector drawables with clip paths should be displayed correctly now.
By the way, since the v1.5.0 of Android Plugin for Gradle you may want to use its feature of automatic generation of PNGs from vector drawables at build time instead of the lib.

Feel free to write if you still have any issues. Have a nice day!

**Comment by Vasilevsrus** [comment]
Thank you! Now everything works well as I see.
